[package]
name = "fim"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.0", features = ["sqlite",  "returning_clauses_for_sqlite_3_35"] } # or `mysql` or `sqlite`
dotenvy = "0.15"
rand = "0.8"
clap = { version = "4.5.19", features = ["derive"]}
anyhow = "1.0.89"
indicatif = "0.17.8"
log = "0.4.22"
env_logger = "0.11.5"
chrono = "0.4.38"

[dev-dependencies]
predicates = "3.1.2"
assert_cmd = "2.0.14"


[lib]
doc = false