// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

pub struct Bucket {
    pub bucket_id: i32,
    pub name: Option<String>,
    pub item_weight: Option<i32>,
}
#[derive(Debug)]
pub struct BucketSort {
    pub bucket_id: i64,
    pub name: String,
    pub epigram_count: f64,
    pub item_weight: i64,
}


pub struct Epigram {
    pub epigram_uuid: String,
    pub bucket_id: Option<i64>,
    pub created_date: Option<String>,
    pub modified_date: Option<String>,
    pub last_impression_date: Option<String>,
    pub content_source: Option<String>,
    pub content_text: Option<String>,
    pub content: Option<String>,
    pub source_url: Option<String>,
    pub action_url: Option<String>,
    pub context_url: Option<String>,
    pub gpt_completion: Option<String>,
    pub favorite: Option<bool>,
}

pub struct Impression {
    pub bucket_id: Option<i32>,
    pub epigram_uuid: Option<String>,
    pub impression_date: Option<String>,
    pub saved: Option<bool>,
    pub gpt_completion: Option<String>,
}

