// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::offset::Local; // Import to get the local time
use chrono::DateTime;      // For handling DateTime object
use diesel::prelude::*;
use diesel::sql_types::Bool;

#[derive(Queryable, Selectable, Insertable)]
#[diesel(primary_key(bucket_id))]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
#[diesel(table_name = crate::schema::bucket)]
pub struct Bucket {
    pub bucket_id: i32,
    pub name: Option<String>,
    pub item_weight: Option<i32>,
}

#[derive(Queryable, Selectable, Debug)]
#[diesel(primary_key(bucket_id))]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
#[diesel(table_name = crate::schema::bucket_sort)]
pub struct BucketSort {
    pub bucket_id: i32,
    pub name: Option<String>,
    pub epigram_count: i32,
    pub item_weight: Option<i32>,
}


#[derive(Queryable, Selectable)]
#[diesel(primary_key(epigram_uuid))]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
#[diesel(table_name = crate::schema::epigram)]
pub struct Epigram {
    pub epigram_uuid: String,
    pub bucket_id: Option<i32>,
    pub created_date: Option<String>,
    pub modified_date: Option<String>,
    pub last_impression_date: Option<String>,
    pub content_source: Option<String>,
    pub content_text: Option<String>,
    pub content: Option<String>,
    pub source_url: Option<String>,
    pub action_url: Option<String>,
    pub context_url: Option<String>,
    pub gpt_completion: Option<String>,
    pub favorite: Option<bool>,
}

#[derive(Selectable, Insertable)]
#[diesel(primary_key(impression_id))]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
#[diesel(table_name = crate::schema::impression)]
pub struct Impression {
    pub bucket_id: Option<i32>,
    pub epigram_uuid: Option<String>,
    pub impression_date: Option<String>,
    pub saved: Option<bool>,
    pub gpt_completion: Option<String>,
}

